tempest: Fixing tempest-icehouse dependencies
While building tempest role, we had the following issue :

 Error: Package: openstack-tempest-icehouse-20141105-1.el7.noarch (openstack-icehouse)
            Requires: python-pbr

This have to be fixed by keeping epel enabled during the tempest-icehouse installation.

This patch does move the remove_epel call _after_ the package installation.