tempest: Fixing setuptools update
The pip update failed and regarding many thread I read, easy_install
works better in such case.

In fact, that was true. Since the switch, the job doesn't fail anymore
with :

-> chroot /var/lib/debootstrap/install/C6.5-I.1.2.0/install-server bash -c 'cd /opt/tempest-report; python ./setup.py install'
/usr/lib/python2.6/site-packages/pbr/core.py:128: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python2.6/site-packages/pbr/core.py:128: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.6/site-packages/pbr/core.py:128: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python2.6/site-packages/pbr/core.py:128: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
Traceback (most recent call last):
  File "./setup.py", line 19, in <module>
    setuptools.setup(setup_requires=['pbr'], pbr=True)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/pbr/packaging.py", line 407, in run
    and self.distribution.install_requires):
AttributeError: Distribution instance has no attribute 'install_requires'