openstack-full/CentOS: install libunwind from EPEL
To solve:
Error: Package: gperftools-libs-2.1-1.el7.x86_64 (ceph)
           Requires: libunwind.so.8()(64bit)